### ISSUE TITLE
fix: output contract verification information in compatible format

### ISSUE THREAD

**Issue by anna-carroll** [nomad-xyz/monorepo#103]
"compatible format" depends on the code written in #124 

- in the past it was an array of verification inputs, one file per chain
- presently, the deploy script creates one file for all chains - a map of network -> array of verification inputs

**Comment by yourbuddyconner** [comment]
Request: 

Based on the discussion in #124, we're solidifying on the pattern of verifying the `core` and `bridge` contracts independently of one-another. The ideal format for the `verification.json` file is as follows: 

``` json
{
    "<network>": {
        "core": {
            // CORE CONTRACT VERIFICATION INPUTS
        }, 
        "bridge": {
            // BRIDGE CONTRACT VERIFICATION INPUTS
        }
    }
}
```
