### ISSUE TITLE
feat: restart-safe deploys

### ISSUE THREAD

**Issue by anna-carroll** [nomad-xyz/monorepo#115]
Right now, if the deploy script throws at any point in the process, you have to restart from zero

Thus far, the deploy script has been prone to some instability due to 
- RPC endpoint rate limiting the code (hard to fix)
- too slow gas price or too low gas limit set in overrides (fixable by hard-coding high values, though this kinda sucks in production)
And a myriad of other potential developer errors or ephemeral problems like internet or network instability

It would be dope if you could re-run the deploy script when it fails and it would pick up where it left off

**Comment by anna-carroll** [comment]
Another thing about this is: we'd need to add checks for each governance tx to check on-chain whether they have been run yet & only attempt them if they have not been run yet

**Comment by anna-carroll** [comment]
> Another thing about this is: we'd need to add checks for each governance tx to check on-chain whether they have been run yet & only attempt them if they have not been run yet

i did this! :)

**Comment by anna-carroll** [comment]
> * write the config to a local file _every time_ a new contract is deployed, so if the script throws, it has stored all of the successful deploys

wait actually.. instead of cacheing after each contract deploy, is it literally as simple as 
- add a try/catch block around the contents of deployAndRelinquish
- if it throws, cache the config in the catch block, then throw the error again? 

@prestwich referred to this in TODO list in his PR #15

**Comment by prestwich** [comment]
this could also be done with `.catch` blocks on promises
