### ISSUE TITLE
feat: make package for verifying contracts (port from old deploy)

### ISSUE THREAD

**Issue by anna-carroll** [nomad-xyz/monorepo#124]

**Comment by yourbuddyconner** [comment]
Proposal for how to implement this: 
- extract existing verification code ([lives here](https://github.com/nomad-xyz/monorepo/tree/main/packages/deploy/src/verification)) and insert into a new package `@nomad-xyz/explorer-verification` 
- Commit existing `verification.json` files (outputted by `@nomad-xyz/new-deploy`) to the package structure such that each time we deploy, the new verification "inputs" that are outputted by the deployment are committed to this package 
  - ex. verification inputs stored in  `<package_root>/verification_inputs/development/verification.json`, etc. 
- Modify the existing code such that it relies upon these built-in verification inputs by default. 
- Edit existing hardhat configuration in the various contract packages (`contracts-core`, `contracts-bridge`) such that it runs the verification process via `@nomad-xyz/explorer-verification`


Overall, it doesn't seem that the verification code as it exists requires much modification outside of switching the external filesystem dependencies on verification inputs to be package-local file dependencies.

**Comment by yourbuddyconner** [comment]
Other notes: 
- This package will be designed to be run in context with a [Hardhat Runtime Environment](https://hardhat.org/advanced/hardhat-runtime-environment.html), like the code is currently designed. Right now, the code is designed to be executed via a custom Hardhat Task [like so](https://github.com/nomad-xyz/monorepo/blob/9415958035a85d38e570f85cce06a6e97c962c8e/packages/contracts-bridge/hardhat.config.ts#L14-L21), we will maintain this functionality.

**Comment by anna-carroll** [comment]
- not sure we should actually commit verification inputs to this package - or anywhere. we actually want to be able to output the verification inputs deterministically based on a config, as part of making deploy script restart-safe: https://github.com/nomad-xyz/monorepo/issues/143
- is there a reason not to use a hardhat task within the `explorer-verification` package itself? instead of `contracts-core`, `contracts-bridge`?
- general note, it would be nice to think of / write this package in a nomad-agnostic way 🤓  just, "verify contracts on any chain."

**Comment by anna-carroll** [comment]
- what about following same structure as `new-deploy` package, which takes an arbitrary file path from argv, to get the location of the verification inputs?

**Comment by yourbuddyconner** [comment]
> not sure we should actually commit verification inputs to this package
This is actually fine with me, assuming the constructor arguments and contract addresses are deterministic even post-deploy. 

> is there a reason not to use a hardhat task within the explorer-verification package itself?
Currently the way this code is structured has an external package passing in a pre-configured HRE. It does it like this because the contract source code will be in-scope of that HRE and nothing is required to get access to that from within the explorer verification code. 

We could pass in the contract source code to build UX like you describe here, however that would require a rewrite of the structure of the current codebase to make it more generalized which would take more time (which I think is ok actually, more generalized more better). 

> what about following same structure as new-deploy package, which takes an arbitrary file path from argv, to get the location of the verification inputs?

Assuming we're alright with generalizing this across the board (and the time that might take), I think this is totally kosher.

**Comment by anna-carroll** [comment]
> assuming the constructor arguments and contract addresses are deterministic even post-deploy

they are!! based on the information in the config 😏 

> the contract source code will be in-scope of that HRE and nothing is required to get access to that from within the explorer verification code

ahhhhh yes i forgot about this urgh sorry, it's late

**Comment by anna-carroll** [comment]
hmmmmmm okay urgh it might make the most sense _for now_ to just call the task within `contracts-core` and `contracts-bridge` with the configured HRE like originally proposed

the deploy script does output bridge and core verification inputs to the same file, tho. but also, verification fails gracefully if it fails for one contract 🤔

**Comment by yourbuddyconner** [comment]
Awesome, I think we can make quick work of the above proposal -- a nomad-specific "hardhat plugin" package which is designed to be run from the context of an existing contracts package (aka `contracts-core` and `contracts-bridge`) and consumes a `verification.json` that is generated on-the-fly at runtime. 

Note: will need to identify the critical path to generating this `verification.json` file

**Comment by anna-carroll** [comment]
> that is generated on-the-fly at runtime

i would instead recommend, a `verification.json` that is consumed from a passed-in filepath

**Comment by yourbuddyconner** [comment]
> the deploy script does output bridge and core verification inputs to the same file, tho. so the script from core would fail for bridge contracts and vice versa.

Ok this will require some finagling... Does it at least output them into distinct `<network>.core` and `<network>.bridge` keys in the `verification.json` file? If not, can it be made so such that we can do bridge and core verification in distinct steps?

**Comment by anna-carroll** [comment]
it does not output them to distinct keys, it puts them in the same keys, but it could be modified to do so (see: https://github.com/nomad-xyz/monorepo/issues/103 - the 🌝  to this ticket's 🌞

**Comment by yourbuddyconner** [comment]
> see: https://github.com/nomad-xyz/monorepo/issues/103 
Awesome, will make notes there.

**Comment by anna-carroll** [comment]
so, note that an HRE is configured with a single chain at a time, and does not natively have the ability to toggle between chains in one process

this is.. annoying

in the old world, we had to simply run the script once per chain... realistically this is tolerable though because you only want to verify a chain once, so when you deploy one new chain you only want to run the script for that chain

**Comment by yourbuddyconner** [comment]
Yes, makes sense to me. This verification package will only be set up to verify packages on one network (the network that is configured in the `hre` that is passed as input at runtime).
