### ISSUE TITLE
bug: indexer query

### ISSUE THREAD

**Issue by ErinHales** [nomad-xyz/monorepo#281]
Specify the amount per page. By default, it returns 15 even though I set it to 10. Daniil said this should work, so it's likely there is a bug: https://bridge-indexer.prod.madlads.tools/tx?amount=10&page=1

**Comment by ErinHales** [comment]
It looks like this query should actually be `size`, however, I'm getting a 502 error now.  I'll play around with it and see if I can figure out the correct query

**Comment by kekonen** [comment]
Fixed in [PR](https://github.com/nomad-xyz/monorepo/pull/293)
