### ISSUE TITLE
Add Support for Candle 

### ISSUE THREAD

**Issue by samisbakedham** [nomad-xyz/monorepo#324]
### Package

contracts-bridge, deploy, sdk-bridge

### Describe the feature you would like

Add support for another network/chain - Candle. (EVM Compatible)

### Additional context

https://github.com/nomad-xyz/monorepo/pull/337#issue-1260870949

**Comment by odyslam** [comment]
Closing as we have already closed the PR

**Comment by samisbakedham** [comment]
> Closing as we have already closed the PR

But was it added?
