### ISSUE TITLE
GitHub actions build step takes 10m due to accumulator-cli

### ISSUE THREAD

**Issue by odyslam** [nomad-xyz/monorepo#353]
### Package

not applicable (please describe)

### At a high level, what are you trying to do?

Use the accumulator-cli in the contract tests

### Describe the bug

We are building from the source the accumulator-cli + installing the rust toolchain. This takes too long and drags the entire `yarn build` process

Possible paths to fix this
- Cache the binary
- Build the binary once and deliver it 

Ping @prestwich for ideas

**Comment by prestwich** [comment]
like we talked about at the time, should build a binary for each arch, and retrieve them from a static host

**Comment by odyslam** [comment]
Fixed
