### ISSUE TITLE
Investigation on Nomad CTO and bounty campaign on Nomad founders and its VCs and partners backers

### ISSUE THREAD

**Issue by James8T** [nomad-xyz/monorepo#483]
### Package

contracts-bridge, contracts-core, contracts-router, deploy, indexer, local-environment, multi-provider, sdk-bridge, sdk-govern, sdk, not applicable (please describe)

### At a high level, what are you trying to do?

Nomad Hack

### Describe the bug

Here the investigation : https://forum.celo.org/t/optics-recovery-mode/2452

I urge FBI to arrest Nomad CTO asap. We have been waiting long enough and stayed in the dark for a long time. Nomad CEO has to do an AMA session with victims to respond to questions.

The team are rich crypto guys, the CEO Pranay even invest in venture like LI.FI : https://medium.com/@jamestrulard/pranay-mohan-invested-into-5m-sround-lifi-protocol-700d05c8c678 

Without notice, a bounty campaign will be launch to prevent more time lost on Nomad founders and its VCs and partners backers. Big noise will be financed with multi 7 figures usd. I urge Nomad to put all transparency on the table right now. 

What is happening is unprecedented, we have to oppen discussion asap , some people can not even hit their house and pay scolarships to their childrens !

**Comment by prestwich** [comment]
please keep GitHub issues to technical subjects, thanks! you're welcome to email recovery@nomad.xyz with any questions

**Comment by James8T** [comment]
They did not answer to my questions. I can not pay scholarships to my son because of you!  $ETH recovery rate will be near zero as almost all $ETH are hold by 1 hacker address who will NOT return funds. Also I receive death threats for debt I have but you have lost my money in your custodian-bridge ( team control via multisig proxy crucial updates ). ☠️☠️💀💀

Who said « users first » « security first » and misleaded users!??!!? Nomad founders. Take responsibilities !!!! 

——> I want You and founders of Nomad  contribute with your own money. You are paid high salaries, have ton of saving to have worked in High marketcap projects like Celo and Storj .
