### ISSUE TITLE
Make sure not to do same transactions multiple time during deploy

### ISSUE THREAD

**Issue by kekonen** [nomad-xyz/monorepo#84]
In the `new-deploy` we have multiple calls which are used several times during deployment. For instance `enrollWatchers`, is reused 2 times, in: `enrollCores` and `enrollRemotes`. Before making a transaction we should first make some checks that the job won't be done twice (hence gas paid twice).

**Comment by prestwich** [comment]
do we have more specific examples? this one is fixed in [2013d53](https://github.com/nomad-xyz/monorepo/pull/15/commits/2013d53206577bfc94f31770845da97eb60be122). Any others should be considered bugs at this point

**Comment by kekonen** [comment]
@prestwich  Same with `enrollGovernanceRouter`. That must be it for now

**Comment by anna-carroll** [comment]
closed by https://github.com/nomad-xyz/monorepo/pull/142
